# Generated by Django 2.2.2 on 2019-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('types', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
